useReduce implemented in gamecontext
navikt/kviss pull request #100
Opened 2022-07-22 13:04 UTC by MatiasGranHenriksen

2022-07-22 13:51 UTC, EmelijonJ approved these changes
I trust the front end boys

2022-07-22 13:51 UTC, EmelijonJ commented on web/app/routes/start/index.tsx
>          const res = await fetch(`http://0.0.0.0:8080/game/${quizId}/gamestart`)
```suggestion
        const res = await fetch(`https://kviss-api.dev.nav.no/game/${quizId}/gamestart`)
```
Maybe change

2022-07-25 06:20 UTC, Henrhh requested changes
Fix type any, make an interface if needed

2022-07-25 06:20 UTC, Henrhh commented on web/app/context/game/game.ts
> +    payload?: any
Why type any?

2022-07-25 08:09 UTC, MatiasGranHenriksen commented on web/app/context/game/game.ts
> +    payload?: any
Fixed, payload set to String temporary

2022-07-25 08:17 UTC, Henrhh approved these changes
sure why not

2022-07-25 11:21 UTC, merged